name: raionbp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  flutter_secure_storage: ^10.0.0
  fpdart: ^1.2.0
  google_fonts: ^8.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  http: ^1.6.0
  persistent_bottom_nav_bar_v2: ^6.2.0
  skeletonizer: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
